version: '3'

services:
  app:
    image: jwilder/whoami
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.port=8000"
        - "traefik.backend=app-${APP_ID}"
        - "traefik.backend.loadbalancer.swarm=false"
        - "traefik.frontend.rule=PathPrefix:/apps/${APP_ID}"

networks:
  traefik:
    external: true
