version: '3'

services:
  app:
    image: phjardas/testapp:${VERSION:-1.0.1.0}
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 4
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.backend=app-${APP_ID}"
        - "traefik.backend.loadbalancer.swarm=false"
        - "traefik.frontend.rule=PathPrefix:/apps/${APP_ID}"
      update_config:
        parallelism: 1
        delay: 5s
        monitor: 5s

networks:
  traefik:
    external: true
