#!/bin/bash

REGISTRY=docker-registry-maint.bd4travel.com:5000
BUILD_NUMBER=${BUILD_NUMBER:-dev}
TAG=${REGISTRY}/info:0.1.${BUILD_NUMBER}

PULL=
PUSH=false

while (($#)); do
  case $1 in
    --pull)
      PULL="--pull"
      ;;
    --push)
      PUSH=true
      ;;
    *)
      echo "unknown argument: $1" >&2
      exit 2
  esac
  shift
done

docker build --rm --force-rm --tag $TAG $PULL .

echo "Built $TAG"

if [ "$PUSH" == "true" ]; then
  docker push $TAG
fi
